language: python

branches:
  only:
  - master

matrix:
  include:
  - name: "Python 3.6 - linux"
    env: PYTHON_VERSION=3.6
    os: linux
  - name: "Python 3.7 - linux"
    env: PYTHON_VERSION=3.7
    os: linux
  - name: "Lint"
    env: PYTHON_VERSION=3.7
    os: linux
    script:
    - black . --diff --check

addons:
    apt:
        packages:
            - libhidapi-dev
            - libudev-dev
            - libusb-1.0-0-dev

install:
    - pip install -r requirements.txt
    
script:
    - python setup.py install
