language: python

python: 
  - "3.6"

addons:
    apt:
        packages:
            - libhidapi-dev
            - libudev-dev
            - libusb-1.0-0-dev

install:
    - pip install -r requirements.txt
    
script:
    - python setup.py install
