name: Test
on: [push]
env:
  python_version: '3.9'

jobs:

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - run: echo Perfoming lint check...
      - name: Check out repository code
        uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ env.python_version }}
      - name: Lint with Pre-commit
        run: pip install pre-commit && pre-commit run --all-files
